baseURL = 'https://codyv.dev/'
locale = 'en-us'
title = 'Cody VerKuilen'
theme = 'codyvdev'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
	weight = 20

  [[menus.main]]
    name = 'Slash'
    pageRef = '/slashes'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
